@Freethings_HostAddress = http://localhost:5289
@userId = 00000000-0000-0000-0000-000000000001
@auctionId = 00000000-0000-0000-0000-000000000001

### Claim auction item

POST {{Freethings_HostAddress}}/api/users/{{userId}}/auctions/{{auctionId}}/claim
Content-Type: application/json

