@Freethings_HostAddress = http://localhost:5289
@userId = d695f6d4-4561-46b2-b0eb-7b0be13d9580

### Add offer

POST {{Freethings_HostAddress}}/api/users/{{userId}}/offers
Content-Type: application/json

{
  "title": "Offer 1",
  "description": "Offer 1 Description"
}

### Get offers

GET {{Freethings_HostAddress}}/api/users/{{userId}}/offers
Content-Type: application/json

### Get offer
@offerId = 

GET {{Freethings_HostAddress}}/api/users/{{userId}}/offers/{{offerId}}

